name: elearning-django-graphene

networks:
  app-network:
    driver: bridge

volumes:
  elearning-psql-volume:
  redis-volume:
  minio-volume:

services:
  postgres-db:
    image: postgres:latest
    container_name: elearning-postgres
    networks:
      - app-network
    volumes:
      - elearning-psql-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: elearning_db
    mem_limit: 521mb   
    
  elearning-django:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: elearning-django
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
    mem_limit: 1024m  
    stdin_open: true 
    tty: true
    depends_on:
      - postgres-db
  
  redis-db:
    image: redis:latest
    container_name: elearning-redis
    networks:
      - app-network
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
    mem_limit: 256m
  
  minio-storage:
    image: quay.io/minio/minio
    container_name: elearning-minio
    networks:
      - app-network
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: user123
      MINIO_ROOT_PASSWORD: pass123123
    command: server /data --console-address ":9001"
    volumes:
      - minio-volume:/data
